// Generated by CoffeeScript 1.8.0
define(['jquery'], function($) {
  return {
    setting: function(e) {
      var setting;
      setting = $(e.target);
      if (this.feature.settingShowed != null) {
        delete this.feature.settingShowed;
        return setting.popover('hide');
      } else {
        setting.attr('data-content', '<div id="setting-container"><div>');
        setting.popover({
          html: true
        });
        setting.popover('show');
        app.startFeature('profile/info', {
          container: $('#setting-container'),
          ignoreExists: true
        });
        return this.feature.settingShowed = {};
      }
    }
  };
});
