// Generated by CoffeeScript 1.7.1
(function() {
  define({
    minMenu: function() {
      var el;
      el = this.feature.layout.$el;
      el.toggleClass('menu-min');
      this.$('btn').toggleClass('icon-double-angle-right');
      if (el.hasClass('menu-min')) {
        return $('.open > .submenu').removeClass('open');
      }
    }
  });

}).call(this);
