// Generated by CoffeeScript 1.7.1
define(['jquery'], function($) {
  return {
    layout: {
      regions: {
        box: "widget-box"
      }
    },
    views: [
      {
        name: 'widget-box',
        region: 'box'
      }
    ]
  };
});
