// Generated by CoffeeScript 1.7.1
(function() {
  define({
    layout: {
      regions: {
        innerHeader: 'inner-header'
      }
    },
    views: [
      {
        name: 'inline:inner-header',
        region: 'innerHeader',
        avoidLoadingHandlers: true
      }
    ]
  });

}).call(this);
