// Generated by CoffeeScript 1.8.0
define({
  layout: {
    regions: {
      title: 'title',
      dropdown: 'dropdown'
    }
  },
  views: [
    {
      name: 'inline:title',
      region: 'title',
      avoidLoadingHandlers: true
    }, {
      name: 'inline:dropdown',
      region: 'dropdown',
      avoidLoadingHandlers: true
    }
  ]
});
