// Generated by CoffeeScript 1.7.1
(function() {
  define({
    layout: {
      regions: {
        title: 'title',
        dropdown: 'dropdown'
      }
    },
    views: [
      {
        name: 'inline:title',
        region: 'title',
        avoidLoadingHandlers: true
      }, {
        name: 'inline:dropdown',
        region: 'dropdown',
        avoidLoadingHandlers: true
      }
    ]
  });

}).call(this);
