INSERT INTO `CDE_DEPARTMENT` (`F_ID`, `F_CODE`, `F_DELETED`, `F_NAME`, `F_PATH`, `F_RANK`, `F_PARENT_ID`)
VALUES
	('d-1001',NULL,0,'研发部',NULL,NULL,NULL),
	('d-1002',NULL,0,'人资部',NULL,NULL,NULL),
	('d-1003',NULL,0,'综合部',NULL,NULL,NULL),
	('d-1004',NULL,0,'财务部',NULL,NULL,NULL),
	('d-1009',NULL,0,'领导',NULL,NULL,NULL);
