// Generated by CoffeeScript 1.7.1
define(["jquery", "vendors/marked.min", "vendors/highlight.pack"], function($, marked) {
  return {
    avoidLoadingHandlers: true,
    extend: {
      afterRender: function() {
        return $('pre code').each(function(i, block) {
          var md;
          if ($(block).hasClass('lang-markdown')) {
            md = $(block).text();
            $(block).parent().after('<div class="marked">' + marked(md) + '</div>');
            $('div.marked pre code').each(function(i, block) {
              return hljs.highlightBlock(block);
            });
            return $(block).parent().remove();
          } else {
            return hljs.highlightBlock(block);
          }
        });
      },
      templateHelpers: function() {
        var codeFeature, obj, scaffold;
        codeFeature = this.feature.startupOptions.codeFeature;
        scaffold = this.feature.startupOptions.scaffold;
        obj = {};
        $.ajax({
          url: 'invoke/code?feature=' + codeFeature + '&scaffold=' + scaffold,
          type: 'get',
          data: {},
          async: false
        }).done(function(data) {
          obj.sources = data.results;
          return obj;
        });
        return obj;
      }
    }
  };
});
